### ISSUE TITLE
Power on System without keypads connected

### ISSUE THREAD

**Issue by rgillam100** [mattsaxon/HASS-SpeakercraftMediaPlayer#9] opened 2022-01-18 09:59 UTC
Hi Matt

Are you able to switch on the first Zone with out using a key pad?
I have an MZC66 which I can configure by using the EZtools software. 
However all the messages I send using the MCZ code emulator tool are ignored (let me know if you don't have this i can send it to you?)
I looks like the system needs an event from keypad or IR to switch the system on , is this correct?

Thanks
Rob

**Comment by mattsaxon** [comment] 2022-01-18 15:47
I believe it is possible to control the system without keypads. In my setup I have 2 keypads and 4 zones controlled. But despite the keypads being attached, I don’t need to use them for anything. However your system does need setting up correctly via EZ tools ‘as if’ there are keypads setup.

**Comment by sjeffrey101** [comment] 2022-01-18 23:01
i have no keypads at all and this works well.  fairly basic EZTools config.  I found the emulator not to be overly good

**Comment by sjeffrey101** [comment] 2022-01-26 18:37
@rgillam100 just looking at this again.  I think in EZ-Tools i may have had to tell the system there is a keypad connected - even thought there isnt.  Can you try that?

Also i cant find my copy of the emulator now, would you be able to send it to me?

**Comment by mattsaxon** [comment] 2022-01-29 16:01
@rgillam100 I've confirmed on my system today that you need the keypad configured as @sjeffrey101 suggests and that this can be done in EZ Tools even though there isn't a physical one.

When you do this, you should see in the emulator that you are getting status messages from each zone that is configured. 

As an example, I have the MZC-66, but with 4 channels configured, and only 2 keypads. I can control the 4 ones via this integration.

**Comment by rgillam100** [comment] 2022-02-02 19:33
@sjeffrey101 
The tool can be found here
https://drive.google.com/drive/folders/1eh8aEXMUwEk0bAqLuahTVGtUom5KNO22?usp=sharing

**Comment by rgillam100** [comment] 2022-02-02 19:45
@mattsaxon I am really tearing my hair out over this. I have now brought a keypad and proved that my system works fine. I can upload the config with EZ tools to the MZC-66 and also verify it. 
I still can not turn on or read anything from my RSA 1.0 (I have 2)
My rs232 experience is pretty good, I have a break out box and can see the messages from the PI are being sent. I have crossed RX and TX, tried all combinations of CTS DSR. Still no luck.
I have a couple of questions, are you using a special cable to connect the RSA 1.0 to the MZC?  I just have a normal patch cable, the power light comes on the RSA so I am it assuming it ok?
Does the activity light flash when you send a command ? I do not see anything on mine?
I have added the RSA 1.0 to my EZ tool configuration, but see little to setup, is there something  else to configure other than the address?

**Comment by mattsaxon** [comment] 2022-02-02 19:49
So I think we've found the issue, neither myself nor @sjeffrey101 are using an RSA1.0 box, we direct connect from HA to the jack connector on the back of the MZC. 

We both connect like this HA->(USB->DB9)(DB9->3.5mm Jack)->MZC

The USB->DB9 connector is a standard off the shelf type USB to Serial cable which will be active. 
The DB9->Jack, I don't recall, but it is a passive device. I don't think any CTS DSR is used here, there are simply not enough connections ;-)

Actually I do recall, mine is a Speakercraft cable which is used to configure the MZC via EZ Tools, I suspect it came "in the box"

**Comment by sjeffrey101** [comment] 2022-02-02 20:26
i got a cable like this from ebay.  [https://www.ebay.co.uk/itm/233733561115?hash=item366b9b1b1b:g:PRsAAOSwal5YKe~c](https://www.ebay.co.uk/itm/233733561115?hash=item366b9b1b1b:g:PRsAAOSwal5YKe~c)

like matt, plugged directly into the mzc.

Ive been tring to get hold of a RSA for ages, because from my understanding it handles the command window for you, so the serial interface out of the RSA is alot less chatty.  But this means it wont work with out component (currently) howver, i dont think it would take much to get it working.

So I presume when you are using the emulator, you have it in RSA mode.

From what i gather the address is the only thing to configure.  You should be seeing the status updates from the serial every 2 seconds, even before you send anything on the serial.

I take it you are on the latest firmware? 2.2.8.  [https://www.speakercraft.com/dealer-resources/](https://www.speakercraft.com/dealer-resources/)

the serial must be working if you can program via ESP-Tools.  are you doing this direct or thorugh the RSA?

**Comment by rgillam100** [comment] 2022-02-03 10:31
@sjeffrey101 
I tried the control port before I brought the RSA, All I get is 0x11 0x13  coming out which I believe is correct. I am sending the 0x55 command  string straight after the 0x11, I have tried this and get no response.
I am on 2.1.4 firmware the link you sent was for the MRA-664 do you have the 2.2.8 for MCZ-66?

**Comment by sjeffrey101** [comment] 2022-02-03 10:34
@rgillam100 the firmware is right down the very bottom, under legacy - with esptools.

ok the 11/13 is it opening and closing the command window, so thats good as you are atleast seeing it send something.

It wont send the zone updates unless the zones are setup in ESP-Tools.  - they need a keypad attaching in the config, even if you dont have any keypads.

I would suggest you upload the one of the default projects from ESP-tools as a test.

**Comment by rgillam100** [comment] 2022-02-03 14:33
@sjeffrey101  I have the default config downloaded, the one that configures all the keypads. but only have one keypad connected. 
![Screenshot 2022-02-03 at 14 09 52](https://user-images.githubusercontent.com/26435491/152362873-11b893c6-5c3e-4d5c-a148-c0a67cc54d71.png)

I still don't see the firmware, only EZ tools and the firmware updater

**Comment by mattsaxon** [comment] 2022-02-03 14:41
You download the firmware updated

**Comment by rgillam100** [comment] 2022-02-03 15:54
Ah, thanks I was looking for a file

**Comment by rgillam100** [comment] 2022-02-03 17:30
@mattsaxon @sjeffrey101 
I updated the firmware and all works !!!
Thank you!!

**Comment by sjeffrey101** [comment] 2022-02-03 17:36
Grest.  So you can now fully control the MZC with our integration?

**Closed as completed** 2022-03-04 23:19 UTC
Labels: question
